# Generated by Django 6.0.6 on 2026-06-24 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Acorde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FamiliaOlfativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="notas/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Perfume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("marca", models.CharField(max_length=200)),
                ("volumen_ml", models.PositiveIntegerField(help_text="Volumen en ml")),
                ("descripcion", models.TextField(blank=True)),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            ("hombre", "Hombre"),
                            ("mujer", "Mujer"),
                            ("unisex", "Unisex"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "longevidad",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("baja", "Baja (1-3h)"),
                            ("moderada", "Moderada (4-6h)"),
                            ("alta", "Alta (7-10h)"),
                            ("muy_alta", "Muy Alta (10h+)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "estela",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("intima", "Íntima"),
                            ("moderada", "Moderada"),
                            ("fuerte", "Fuerte"),
                            ("muy_fuerte", "Muy Fuerte"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "uso",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dia", "Día"),
                            ("noche", "Noche"),
                            ("ambos", "Día y Noche"),
                        ],
                        max_length=10,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "acordes",
                    models.ManyToManyField(
                        blank=True, related_name="perfumes", to="catalogo.acorde"
                    ),
                ),
                (
                    "familia_olfativa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="perfumes",
                        to="catalogo.familiaolfativa",
                    ),
                ),
                (
                    "notas",
                    models.ManyToManyField(
                        blank=True, related_name="perfumes", to="catalogo.nota"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImagenPerfume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="perfumes/")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("principal", "Principal"),
                            ("catalogo", "Catálogo"),
                            ("historia", "Historia/Story"),
                            ("banner", "Banner"),
                            ("otra", "Otra"),
                        ],
                        default="principal",
                        max_length=20,
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        help_text="Ej: fondo negro, fondo blanco, con flores...",
                        max_length=200,
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0, help_text="Orden de aparición"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "perfume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="catalogo.perfume",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "creado_en"],
            },
        ),
    ]
