# Generated by Django 6.0.6 on 2026-06-24 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfume",
            name="imagen_portada",
            field=models.ImageField(
                blank=True, null=True, upload_to="perfumes/portadas/"
            ),
        ),
        migrations.CreateModel(
            name="Presentacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("decant", "Decant"),
                            ("original", "Tamaño Original"),
                            ("set", "Set"),
                            ("miniatura", "Miniatura"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("volumen_ml", models.PositiveIntegerField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                (
                    "perfume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presentaciones",
                        to="catalogo.perfume",
                    ),
                ),
            ],
        ),
    ]
