# Generated by Django 6.0.6 on 2026-06-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_perfume_imagen_portada_presentacion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagenperfume",
            options={"ordering": ["creado_en"]},
        ),
        migrations.RemoveField(
            model_name="familiaolfativa",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="imagenperfume",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="imagenperfume",
            name="orden",
        ),
        migrations.RemoveField(
            model_name="perfume",
            name="volumen_ml",
        ),
        migrations.AlterField(
            model_name="presentacion",
            name="volumen_ml",
            field=models.CharField(max_length=20),
        ),
    ]
