# Generated by Django 6.0.6 on 2026-07-09 06:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0003_alter_imagenperfume_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfume",
            name="imagen_portada",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="imagen"
            ),
        ),
    ]
