# Generated by Django 6.0.6 on 2026-07-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0004_alter_perfume_imagen_portada"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="presentacion",
            options={
                "ordering": ["perfume", "volumen_ml"],
                "verbose_name": "presentación",
                "verbose_name_plural": "presentaciones",
            },
        ),
        migrations.AddField(
            model_name="presentacion",
            name="precio_automatico",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="presentacion",
            unique_together={("perfume", "tipo", "volumen_ml")},
        ),
    ]
