# Generated by Django 6.0.6 on 2026-07-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0005_alter_presentacion_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presentacion",
            name="precio_automatico",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
