# Generated by Django 6.0.6 on 2026-09-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0006_alter_presentacion_precio_automatico"),
    ]

    operations = [
        migrations.AddField(
            model_name="acorde",
            name="color",
            field=models.CharField(
                default="#e8e2d5",
                help_text="Color en formato hexadecimal, ej: #e8e2d5",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="nota",
            name="color",
            field=models.CharField(
                default="#e8e2d5",
                help_text="Color en formato hexadecimal, ej: #e8e2d5",
                max_length=7,
            ),
        ),
    ]
