# Generated by Django 6.0.6 on 2026-09-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0007_acorde_color_nota_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="familiaolfativa",
            name="imagen_fondo",
            field=models.ImageField(
                blank=True, null=True, upload_to="familias/fondos/"
            ),
        ),
    ]
