# Generated by Django 6.0.6 on 2026-09-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0008_familiaolfativa_imagen_fondo"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfume",
            name="color_ambiente",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
