# Generated by Django 6.0.6 on 2026-06-30 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0003_alter_imagenperfume_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoApartado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio", models.CharField(editable=False, max_length=20, unique=True)),
                (
                    "cliente_nombre",
                    models.CharField(max_length=150, verbose_name="Nombre del cliente"),
                ),
                (
                    "cliente_telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "cliente_ref",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Referencia / Red social",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierto", "Abierto"),
                            ("liquidado", "Liquidado"),
                            ("entregado", "Entregado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="abierto",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("notas", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="PagoApartado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("transferencia", "Transferencia"),
                            ("deposito", "Depósito"),
                        ],
                        default="efectivo",
                        max_length=20,
                    ),
                ),
                (
                    "comprobante",
                    models.ImageField(blank=True, null=True, upload_to="comprobantes/"),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="apartados.pedidoapartado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["fecha"],
            },
        ),
        migrations.CreateModel(
            name="PedidoApartadoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Precio al momento",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="apartados.pedidoapartado",
                    ),
                ),
                (
                    "presentacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apartado_items",
                        to="catalogo.presentacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto del pedido",
                "verbose_name_plural": "Productos del pedido",
            },
        ),
    ]
