# Generated by Django 6.0.6 on 2026-07-17 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartados", "0001_initial"),
        ("contabilidad", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagoapartado",
            name="movimiento_contable",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pago_apartado",
                to="contabilidad.movimiento",
            ),
        ),
    ]
