# Generated by Django 6.0.6 on 2026-07-23 20:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartados", "0002_pagoapartado_movimiento_contable"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidoapartado",
            name="codigo_qr",
            field=models.ImageField(
                blank=True, null=True, upload_to="codigos_qr/", verbose_name="Código QR"
            ),
        ),
        migrations.AddField(
            model_name="pedidoapartado",
            name="token_publico",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="Token público"
            ),
        ),
    ]
