# Generated by Django 6.0.6 on 2026-07-23 20:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartados", "0003_pedidoapartado_codigo_qr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedidoapartado",
            name="token_publico",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Token público",
            ),
        ),
    ]
