# Generated by Django 6.0.6 on 2026-07-13 17:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0005_alter_presentacion_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Concepto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ingreso", "Ingreso"), ("egreso", "Egreso")],
                        max_length=20,
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "concepto",
                "verbose_name_plural": "conceptos",
                "ordering": ["tipo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionDecant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bolsa_costo",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
                ),
                (
                    "jeringa_costo",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
                ),
                (
                    "porcentaje_ganancia",
                    models.DecimalField(decimal_places=2, default=25.0, max_digits=5),
                ),
                ("redondeo_terminacion", models.CharField(default="5", max_length=1)),
            ],
            options={
                "verbose_name": "Configuración de Decants",
                "verbose_name_plural": "Configuración de Decants",
            },
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "unidad",
                    models.CharField(
                        choices=[("unidad", "Unidad"), ("ml", "Mililitro")],
                        default="unidad",
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "stock_minimo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "inventario",
                "verbose_name_plural": "inventarios",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="HistorialPrecios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio_anterior",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("precio_nuevo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_cambio", models.DateTimeField(auto_now_add=True)),
                ("motivo", models.CharField(blank=True, max_length=255, null=True)),
                ("usuario", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "perfume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_precios",
                        to="catalogo.perfume",
                    ),
                ),
                (
                    "presentacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_precios",
                        to="catalogo.presentacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "historial de precio",
                "verbose_name_plural": "historial de precios",
                "ordering": ["-fecha_cambio"],
            },
        ),
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=2, default=1, max_digits=12),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("confirmado", "Confirmado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="confirmado",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="contabilidad.concepto",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimiento",
                "verbose_name_plural": "movimientos",
                "ordering": ["-fecha", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proveedor", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "cantidad_comprada",
                    models.PositiveIntegerField(
                        help_text="Número de perfumes completos comprados"
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio de compra por unidad",
                        max_digits=10,
                    ),
                ),
                (
                    "costo_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Costo total de la compra",
                        max_digits=12,
                    ),
                ),
                ("fecha_compra", models.DateField(default=django.utils.timezone.now)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("en_proceso", "En Proceso"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="en_proceso",
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "perfume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras",
                        to="catalogo.perfume",
                    ),
                ),
                (
                    "movimiento_contable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compras_asociadas",
                        to="contabilidad.movimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "compra",
                "verbose_name_plural": "compras",
                "ordering": ["-fecha_compra"],
            },
        ),
        migrations.AddIndex(
            model_name="movimiento",
            index=models.Index(fields=["fecha"], name="contabilida_fecha_1f5075_idx"),
        ),
        migrations.AddIndex(
            model_name="movimiento",
            index=models.Index(
                fields=["concepto", "estado"], name="contabilida_concept_f6f422_idx"
            ),
        ),
    ]
