# Generated by Django 6.0.6 on 2026-07-25 21:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0006_alter_presentacion_precio_automatico"),
        ("contabilidad", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompraDecant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proveedor", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "volumen_ml",
                    models.PositiveIntegerField(help_text="Volumen del decant en ml"),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "costo_total",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                ("fecha_compra", models.DateField(default=django.utils.timezone.now)),
                ("notas", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movimiento_contable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compras_decant_asociadas",
                        to="contabilidad.movimiento",
                    ),
                ),
                (
                    "perfume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras_decant",
                        to="catalogo.perfume",
                    ),
                ),
            ],
            options={
                "verbose_name": "compra de decant",
                "verbose_name_plural": "compras de decants",
                "ordering": ["-fecha_compra"],
            },
        ),
        migrations.CreateModel(
            name="CompraInsumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("empaque", "Empaque (bolsas, cajas)"),
                            ("decant", "Material decant (frascos, jeringas)"),
                            ("impresion", "Impresión (impresora, cinta, etiquetas)"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                    ),
                ),
                ("proveedor", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=2, default=1, max_digits=12),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "costo_total",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                ("fecha_compra", models.DateField(default=django.utils.timezone.now)),
                ("notas", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inventario",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vincula al inventario para actualizar stock automáticamente",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compras_insumo",
                        to="contabilidad.inventario",
                    ),
                ),
                (
                    "movimiento_contable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compras_insumo_asociadas",
                        to="contabilidad.movimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "compra de insumo",
                "verbose_name_plural": "compras de insumos",
                "ordering": ["-fecha_compra"],
            },
        ),
    ]
