# Generated by Django 6.0.6 on 2026-06-26 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordencompra", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=200)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("cerrada", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.RemoveField(
            model_name="itemcotizacion",
            name="cotizacion",
        ),
        migrations.RemoveField(
            model_name="itemcotizacion",
            name="perfume",
        ),
        migrations.AlterModelOptions(
            name="proveedor",
            options={"ordering": ["nombre"]},
        ),
        migrations.RemoveField(
            model_name="proveedor",
            name="activo",
        ),
        migrations.RemoveField(
            model_name="proveedor",
            name="contacto",
        ),
        migrations.RemoveField(
            model_name="proveedor",
            name="creado_en",
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="ColumnaCotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "envio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ordencompra.proveedor",
                    ),
                ),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columnas",
                        to="ordencompra.cotizacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FilaCotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("perfume_nombre", models.CharField(max_length=200)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filas",
                        to="ordencompra.cotizacion",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="CeldaCotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "columna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="celdas",
                        to="ordencompra.columnacotizacion",
                    ),
                ),
                (
                    "fila",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="celdas",
                        to="ordencompra.filacotizacion",
                    ),
                ),
            ],
            options={
                "unique_together": {("fila", "columna")},
            },
        ),
        migrations.DeleteModel(
            name="CotizacionProveedor",
        ),
        migrations.DeleteModel(
            name="ItemCotizacion",
        ),
    ]
